### ISSUE TITLE
allow for multiple processing pipelines

### ISSUE THREAD

**Issue by v-nys** [v-nys/learning-paths-tauri-react#44]
Right now, we have "create archive" (or "zip", I forget). What if I want to use the same content for my personal website *and* for my course material? Having two buttons would be easier than commenting stuff out all the time.

Maybe somehting like this:

```yaml
processing_sequences:
  - title: "Create Moodle export"
    plugin_sequence:
      - path: blabla-create-zip.wasm
      - path: blabla-create-local-course.wasm
      - path: blabla-upload-to-gitbook.wasm
      - path: blabla-update-lti-app.wasm
  - title: "Export to personal website"
    plugin_sequence:
      - path: blabla-upload-to-server.wasm
      - path: blabla-notify-subscribers.wasm
```
