### ISSUE TITLE
deal with plugin naming conflicts

### ISSUE THREAD

**Issue by v-nys** [v-nys/learning-paths-tauri-react#8]
There could be several "assignments" plugins, etc. For now, adding a namespacing mechanism seems like a viable solution. E.g. in the yaml file for a cluster:

```yaml
nodes:
  - id: ...
    title: ...
    my_version_of_assignments: ...
  - id: ...
    title: ...
    another_version_of_assignments: ...
plugins:
  - path: ...
    prefix: my_version_of_
  - path: ...
    prefix: alternate_version_of_
```
